server:
  port: 8080
spring:
  redis:
    database: 0
    host: localhost
    port: 6380
    password: zikbo
    connect-timeout: 60000
oauth2:
  client:
    registration:
      headhunter:
        clientId: ${HEADHUNTER_CLIENT_ID:JQGJM6V5NNDRT6PDEHEUF4LDKQF684MU6PNHTO74VAEJ01QGTG3LTVJHBA3QQOOS}
        clientSecret: ${HEADHUNTER_CLIENT_SECRET:PNS48L8OM9N6P470RO7Q22B2KBORAOBABMCPRDEU5N6V9GH7OOFG92MJBE1F7B3A}
        redirectUri: ${HEADHUNTER_REDIRECT_URI:http://localhost:8080/login/oauth2/code/headhunter}
        scope: read:user
    provider:
      headhunter:
        name: headhunter
        authorizationUri: https://hh.ru/oauth/authorize
        tokenUri: https://hh.ru/oauth/token
        userInfoUri: https://api.hh.ru/me
        revokeTokenUri: https://api.hh.ru/oauth/token
        revokePermissionUri: https://api.hh.ru/oauth/token